name: Build BWA-MEM2

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with: 
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build bwa-mem2
        run: |
          cd external/bwa-mem2
          make